### ISSUE TITLE
Clone fails if Feature Service already Exist

### ISSUE THREAD

**Issue by previnWong** [chris-fox/scripts-tools#12]
Trying to clone Isolation Trace Map.  This map has the WaterDistributionNetwork as part of the layers.  This Feature Service already exists in the org I'm trying to clone into, so it throws this error.

---

Parameters
Items   067b19e4be4d4b04a6443a4fd47c86a3
Folder  Clone
Copy Data   true
Validation JSON 

Messages
Start Time: Friday, September 16, 2016 11:07:21 AM
Running script CloneItemsTool...
Cloning Isolation Trace
Failed to create Feature Service WaterDistributionNetwork: Cannot perform query. Invalid query parameters.
Unable to perform query. Please check your parameters.
(Error Code: 400)
Deleted Feature Service WaterDistributionNetwork
## Failed to add Map Notes

Completed script CloneItemsTool...
Failed to execute (CloneItemsTool).
Failed at Friday, September 16, 2016 11:09:28 AM (Elapsed Time: 2 minutes 6 seconds)

**Comment by chris-fox** [comment]
@previnWong, It doesn't look to be related to the feature service already existing. It is failing trying to query features from this layer, http://services1.arcgis.com/ix9EcElgUzvEWNbb/ArcGIS/rest/services/WaterDistributionNetwork/FeatureServer/3. If you set copy data to false, it should work properly, because it doesn't need to query the original features.

You can reproduce the error with this query:

http://services1.arcgis.com/ix9EcElgUzvEWNbb/ArcGIS/rest/services/WaterDistributionNetwork/FeatureServer/3/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=&units=esriSRUnit_Meter&outFields=*&returnGeometry=true&multipatchOption=&maxAllowableOffset=&geometryPrecision=&outSR=3857&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnDistinctValues=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&quantizationParameters=&sqlFormat=none&f=html&token=

It is a really simple query, so not sure why it is failing, seems to fail when I request all the fields. In addition, if you attempt to inspect the data of the Hydrant Value layer at this link, http://www.arcgis.com/home/item.html?id=502ad191f560412d850ba75d3c10c6c8#data, you will see it report there are 1377 features, but the table is empty. 

So to me it seems like something up with this service, but it is not clear what exactly is the issue.
